name: ItemStorage
version: '${project.version}'
main: org.molekula.itemstorage.ItemStorage
api-version: '1.16'
description: An API for saving and loading items in Minecraft
author: molekula0192
commands:
  loaditem:
    description: "Load item by name"
    usage: /<command> <key>
    permission: is.loaditem
    permission-message: ""
  saveitem:
    description: "Save item"
    usage: /<command> <key>
    permission: is.saveitem
    permission-message: ""